/**
 * Provider-neutral contract for the language model. The rest of the app only talks
 * to this interface, so switching providers means writing one new implementation.
 */

/** A piece of the lawyer's library handed to the model as citable evidence. */
export interface GroundingDocument {
  title: string;
  /** Metadata the model can read but not cite (category, file name...). */
  context?: string;
  content: string;
}

export interface GroundedAnswerInput {
  systemPrompt: string;
  question: string;
  documents: GroundingDocument[];
}

export interface AnswerCitation {
  /** Index into GroundedAnswerInput.documents. */
  documentIndex: number;
  /** Exact text taken from that document (not generated by the model). */
  citedText: string;
  startChar: number | null;
  endChar: number | null;
}

export interface AnswerBlock {
  text: string;
  citations: AnswerCitation[];
}

export interface LlmUsage {
  inputTokens: number;
  outputTokens: number;
}

export interface GroundedAnswer {
  blocks: AnswerBlock[];
  /** Model that actually produced the answer (may differ if a fallback ran). */
  model: string;
  usage: LlmUsage;
}

export interface LlmProvider {
  readonly providerName: string;
  readonly model: string;
  generateGroundedAnswer(input: GroundedAnswerInput): Promise<GroundedAnswer>;
}
