/**
 * Provider-neutral contract for the language model. The rest of the app only talks
 * to this interface, so switching providers means writing one new implementation.
 */

/** A piece of the lawyer's library handed to the model as citable evidence. */
export interface GroundingDocument {
  title: string;
  /** Metadata the model can read but not cite (category, file name...). */
  context?: string;
  content: string;
}

export interface GroundedAnswerInput {
  systemPrompt: string;
  question: string;
  documents: GroundingDocument[];
}

export interface AnswerCitation {
  /** Index into GroundedAnswerInput.documents. */
  documentIndex: number;
  /** Exact text taken from that document (not generated by the model). */
  citedText: string;
  startChar: number | null;
  endChar: number | null;
}

export interface AnswerBlock {
  text: string;
  citations: AnswerCitation[];
}

export interface LlmUsage {
  inputTokens: number;
  outputTokens: number;
}

export interface GroundedAnswer {
  blocks: AnswerBlock[];
  /** Model that actually produced the answer (may differ if a fallback ran). */
  model: string;
  usage: LlmUsage;
}

/** A capability the agent may decide to use (search the library, read a document...). */
export interface AgentTool {
  name: string;
  description: string;
  /** JSON Schema of the arguments. */
  parameters: Record<string, unknown>;
  execute(args: Record<string, unknown>): Promise<unknown>;
}

export interface AgentRunInput {
  systemPrompt: string;
  userMessage: string;
  tools: AgentTool[];
  /** Rounds of tool use allowed; after that the model must write its final answer. */
  maxToolRounds: number;
}

export interface AgentToolCall {
  tool: string;
  args: Record<string, unknown>;
  ok: boolean;
  error?: string;
}

export interface AgentRunResult {
  /** The model's final answer (for drafts: the document in Markdown). */
  text: string;
  /** Every tool the model used, in order: kept to debug why a result came out wrong. */
  toolCalls: AgentToolCall[];
  model: string;
  usage: LlmUsage;
}

export interface LlmProvider {
  readonly providerName: string;
  readonly model: string;
  generateGroundedAnswer(input: GroundedAnswerInput): Promise<GroundedAnswer>;
  /** Lets the model call tools in a loop until it produces a final answer. */
  runAgent(input: AgentRunInput): Promise<AgentRunResult>;
}
